#include <Arduino.h>
#include <EEPROM.h>

#include "Mega_Eeprom_Custom.h"
#include "Mega_ESP_Custom.h"
#include "Mega_Global_Custom.h"
#include "Mega_Pump_Custom.h"
#include "Mega_Sensor_Custom.h"

void Mega_Eeprom_Custom :: EEPROM_read()
{
	unsigned char eeprom_status = EEPROM.read(EEPROM_STATUS_ADDRESS);
	if (eeprom_status==0x01)
		{
			PUMP1_TIME = EEPROM.read(PUMP1_DURATION_ADDRESS);
			PUMP2_TIME = EEPROM.read(PUMP2_DURATION_ADDRESS);
			PUMP3_TIME = EEPROM.read(PUMP3_DURATION_ADDRESS);
			PUMP4_TIME = EEPROM.read(PUMP4_DURATION_ADDRESS);
			
			PUMP5_TIME = EEPROM.read(PUMP5_DURATION_ADDRESS);
			PUMP6_TIME = EEPROM.read(PUMP6_DURATION_ADDRESS);
			PUMP7_TIME = EEPROM.read(PUMP7_DURATION_ADDRESS);
			PUMP8_TIME = EEPROM.read(PUMP8_DURATION_ADDRESS);
			
			PUMP9_TIME  = EEPROM.read( PUMP9_DURATION_ADDRESS);
			PUMP10_TIME = EEPROM.read(PUMP10_DURATION_ADDRESS);
			PUMP11_TIME = EEPROM.read(PUMP11_DURATION_ADDRESS);
			PUMP12_TIME = EEPROM.read(PUMP12_DURATION_ADDRESS);
			
			PUMP13_TIME = EEPROM.read(PUMP13_DURATION_ADDRESS);
			PUMP14_TIME = EEPROM.read(PUMP14_DURATION_ADDRESS);
			PUMP15_TIME = EEPROM.read(PUMP15_DURATION_ADDRESS);
			PUMP16_TIME = EEPROM.read(PUMP16_DURATION_ADDRESS);
			
			PUMP17_TIME = EEPROM.read(PUMP17_DURATION_ADDRESS);
			PUMP18_TIME = EEPROM.read(PUMP18_DURATION_ADDRESS);
			PUMP19_TIME = EEPROM.read(PUMP19_DURATION_ADDRESS);
			PUMP20_TIME = EEPROM.read(PUMP20_DURATION_ADDRESS);


			SHT_On_Off_sequence    = EEPROM.read(SHT_ON_OFF_ADDRESS);
//			Moist_On_Off_sequence  = EEPROM.read(MOIST_ON_OFF_ADDRESS);

			System_On_Off_sequence = EEPROM.read(SYSTEM_ON_OFF_ADDRESS);
		}
	else
		{
			EEPROM.write(EEPROM_STATUS_ADDRESS, 0x01);
			EEPROM.write(PUMP1_DURATION_ADDRESS, PUMP1_TIME);
			EEPROM.write(PUMP2_DURATION_ADDRESS, PUMP2_TIME);
			EEPROM.write(PUMP3_DURATION_ADDRESS, PUMP3_TIME);
			EEPROM.write(PUMP4_DURATION_ADDRESS, PUMP4_TIME);
			
			EEPROM.write(PUMP5_DURATION_ADDRESS, PUMP5_TIME);
			EEPROM.write(PUMP6_DURATION_ADDRESS, PUMP6_TIME);
			EEPROM.write(PUMP7_DURATION_ADDRESS, PUMP7_TIME);
			EEPROM.write(PUMP8_DURATION_ADDRESS, PUMP8_TIME);
			
			EEPROM.write(PUMP9_DURATION_ADDRESS,   PUMP9_TIME);
			EEPROM.write(PUMP10_DURATION_ADDRESS, PUMP10_TIME);
			EEPROM.write(PUMP11_DURATION_ADDRESS, PUMP11_TIME);
			EEPROM.write(PUMP12_DURATION_ADDRESS, PUMP12_TIME);
			
			EEPROM.write(PUMP13_DURATION_ADDRESS, PUMP13_TIME);
			EEPROM.write(PUMP14_DURATION_ADDRESS, PUMP14_TIME);
			EEPROM.write(PUMP15_DURATION_ADDRESS, PUMP15_TIME);
			EEPROM.write(PUMP16_DURATION_ADDRESS, PUMP16_TIME);
			
			EEPROM.write(PUMP17_DURATION_ADDRESS, PUMP17_TIME);
			EEPROM.write(PUMP18_DURATION_ADDRESS, PUMP18_TIME);
			EEPROM.write(PUMP19_DURATION_ADDRESS, PUMP19_TIME);
			EEPROM.write(PUMP20_DURATION_ADDRESS, PUMP20_TIME);

			EEPROM.write(SHT_ON_OFF_ADDRESS, SHT_On_Off_sequence);
//			EEPROM.write(MOIST_ON_OFF_ADDRESS, Moist_On_Off_sequence);

			EEPROM.write(SYSTEM_ON_OFF_ADDRESS, System_On_Off_sequence);
		}
}
